# charts/apigee-cassandra/values.yaml
# Valeurs par défaut — systématiquement écrasées par les fichiers
# values/platform/cassandra/values-*.yaml lors du déploiement.

cassandra:
  image:
    repository: "gcr.io/apigee-release/hybrid/apigee-cassandra"
    tag: ""
  auth:
    default:
      password: ""
    secretRef: apigee-cassandra-auth
  tls:
    internodeEncryption: all
    clientEncryption: true
    secretRef: apigee-cassandra-tls
  heapNewSize: 100M
  maxHeapSize: 512M
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
    limits:
      memory: 4Gi
  multiRegion:
    enabled: false
    seedHost: ""
  datacenters: []
  keyspacesReplication: {}

storage:
  storageClass: ""
  size: 500Gi

dc1:
  seedList: []
