tenant: test
apigeeEnv: test
apigeeEnvGroup: nonprod-group
appUID: ap43591
platformEnv: hprd

targetClusters:
  - cluster-A

ingressGateway:
  mode: shared
  sharedGatewayName: apigee-ingress-nonprod

exposition:
  ingressClass: traefik
  hosts:
    - host: api-test.mondomaine.com
      tlsSecretRef: ingress-tls
  targetServiceName: apigee-ingress-nonprod-svc

vault:
  mountPath: secret/ap43591/apigee/test
  gcpServiceAccounts:
    synchronizer: sa-synchronizer.json
    udca: sa-udca.json
    mart: sa-mart.json
    metrics: sa-metrics.json
  tls:
    internalCert: tls/internal
    caBundle: ../ca/internal-ca

runtime:
  replicas: 2
synchronizer:
  replicas: 1

cassandraReplication:
  dc-1: 3
