# values/platform/cassandra/values-dc1.yaml
# Surcharges spécifiques au DC1 (celui sur cluster-A)

dc1:
  # Les 3 seeds nodes initiaux — noms fixes, prédictibles
  seedList:
    - apigee-cassandra-default-0.apigee-cassandra-default.apigee.svc.cluster.local
    - apigee-cassandra-default-1.apigee-cassandra-default.apigee.svc.cluster.local
    - apigee-cassandra-default-2.apigee-cassandra-default.apigee.svc.cluster.local
  # Options JVM spécifiques si DC1 tourne sur des nodes plus petits/plus gros
  # jvm:
  #   additionalOptions: []
