apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ordre de chargement logique — les sync-waves ArgoCD
# sur chaque ressource gèrent l'ordre effectif de réconciliation.
resources:
  - 01-ns-appset.yaml
  - 02-platform-crds-appset.yaml
  - 03-platform-controller-appset.yaml
  - 04-cassandra-app.yaml
  - 05-tenant-secrets-appset.yaml
  - 06-tenant-ingress-appset.yaml
  - 07-tenant-env-appset.yaml
  - 08-tenant-exposure-appset.yaml
